### ISSUE TITLE
V-ray standalone uses port 20207 by default; blender has 20204 configured

### ISSUE THREAD

**Issue by philstopford** [ChaosGroup/blender_with_vray_additions#250]
I don't think I changed anything, but I'm seeing a port mis-match for distributed rendering between the blender/V-ray install and the standalone install. Standalone is listening on 20207; blender is trying to issue commands on 20204.

**Comment by bdancer** [comment]
Not sure what to fix here... Standalone has command line switch "-portNumber=n", port may be set in DR settings as well...

**Comment by philstopford** [comment]
I can set the DR value per-scene, but there is no global setting (in blender/V-ray) that I can find. It's odd because modo/V-ray has the right port setting out-of-the-box. Not sure why the blender/V-ray port is different.

**Comment by bdancer** [comment]
> Not sure why the blender/V-ray port is different.

1. 8 years ago if was developed on Linux and 20204 was default back then.
2. no one reported this since then.
3. You could set it once to the desired value and Ctrl+U to save default scene.
4. You could set it on render node with -portNumber switch.

> has the right port setting out-of-the-box.

Ok: https://github.com/ChaosGroup/vray_for_blender_exporter/commit/5ab0aa2c2b4d7c2b6ab9fc09c3a489bad3462422
